---
name: publish

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest
    env:
      PLATFORMS: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/ppc64le,linux/s390x
      DOCKERHUB_USERNAME: isac322
    steps:
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          flavor: latest=false
          images: ${{ env.DOCKERHUB_USERNAME }}/blackd
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            maintainer=${{ env.DOCKERHUB_USERNAME }}
            org.opencontainers.image.title=blackd
            org.opencontainers.image.source=https://github.com/psf/black
            org.opencontainers.image.documentation=https://black.readthedocs.io

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Load buildkit state
        uses: isac322/buildkit-state@v2
        with:
          buildx-name: ${{ steps.buildx.outputs.name }}

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          build-args: |
            VERSION=${{ steps.docker_meta.outputs.version }}
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
